name: Img2txt

on:
  schedule:
    # At 9:00 AM on the 9th day of the month, Moscow time (UTC+3)
    # Cron times are in UTC so adjust accordingly: 9 AM UTC+3 is 6 AM UTC
    - cron: '0 5 9 * *'
  workflow_dispatch:
  push:
    paths:
      - 'sample.png'
      - '.github/workflows/ocr.yml'
      
jobs:
  easyocr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install easyocr

      - name: Run OCR
        run: |
          python easyocr.py

      - name: Upload OCR result as artifact
        uses: actions/upload-artifact@v4
        with:
          name: easyocr-result
          path: ocr_result.txt
  tesseract:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Install Tesseract
      run: |
        sudo apt-get update
        sudo apt-get install -y tesseract-ocr

    - name: Run OCR
      run: |
        tesseract fsk.jpg output -l eng
        cat tesseract.txt

    - name: Upload OCR result as artifact
      uses: actions/upload-artifact@v4
      with:
        name: ocr-result-tesseract
        path: tesseract.txt

  paddleocr:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies (PaddleOCR)
      run: |
        python -m pip install --upgrade pip
        pip install paddlepaddle==2.6.1
        pip install "paddleocr>=2.6.1.3"
        pip install numpy

    - name: Run recognition
      run: |
        python - <<EOF
        from paddleocr import PaddleOCR
        import os

        ocr = PaddleOCR(use_angle_cls=True, lang='ru')
        result = ocr.ocr('fsk.jpg', cls=True)
        print(result)
        with open("ocr_output.txt", "w", encoding="utf-8") as f:
            if result and result[0]:
                for line in result[0]:
                    text = line[1][0]
                    f.write(text + "\n")
            else:
                print("No text detected.")
        EOF

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: paddleocr-result
        path: ocr_output.txt
