name: Python NLP Script

on:
  workflow_dispatch:
  schedule:
    # At 9:00 AM on the 15th day of the month, Moscow time (UTC+3)
    # Cron times are in UTC so adjust accordingly: 9 AM UTC+3 is 6 AM UTC
    - cron: '0 5 4 * *'
  push:
    branches:
      - 'releases/**'
      - 'master'
  pull_request:
    branches: [ "**" ]

jobs:
  nlp-pipeline:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          cd analysis
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          python -m spacy download ru_core_news_sm  # Install Russian model
          python -m nltk.downloader punkt stopwords wordnet  # Download required NLTK resources

      - name: Run NLP script
        run: |
          python network_trends.py
