name: Python CI

on:
  workflow_dispatch:
  schedule:
    # At 9:00 AM on the 15th day of the month, Moscow time (UTC+3)
    # Cron times are in UTC so adjust accordingly: 9 AM UTC+3 is 6 AM UTC
    - cron: '0 5 4 * *'
  push:
    branches:
      - 'releases/**'
  pull_request:
    branches: [ "**" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Calculate TP index
        run: |
          python tp_index.py
        env:
          TP: ${{ secrets.TP }}
